### ISSUE TITLE
Typo in readme?

### ISSUE THREAD

**Issue by fdecarpentier** [vsbuffalo/savio-snakemake#1]
Thank you for the snakemake profile, it's great!
I think there is a typo, isn't the job argument missing here? It would be something like that:

> Note that this job will use **default resources** and only *two* jobs. This is 
> intentional, since the user should override the number of jobs on the command line
> with 
> 
> ```bash
> $ snakemake --workflow-profile ~/.config/snakemake/savio all --jobs 4
> ```

**Comment by vsbuffalo** [comment]
Thanks Félix! I have made this change. Let me know if you spot any other issues.
